from nicegui import ui

def changelog():
    with ui.card(align_items="center").classes("w-full").style("box-shadow: None; left: -5%"):
        with ui.row():
            ui.button("返回主页", on_click=lambda: ui.navigate.to('/')).style("right: -15%")
            ui.button("GitHub", on_click=lambda: ui.navigate.to('https://github.com/Nya-WSL/bili_travail', new_tab=True)).style("right: -15%")
        with ui.timeline(side='right', layout='comfortable'):
            ui.timeline_entry('B站加班姬更新日志', heading=True)
            ui.timeline_entry(title='Release of 0.23.0-alpha', subtitle='2025-03-12', avatar='static/logo.ico')
            ui.timeline_entry('新增赌⭕统计功能')
            ui.timeline_entry('修复系统语言非utf-8编码可能会导致更新脚本报错的问题')
            ui.timeline_entry('更新预设礼物数据和盲盒数据')
            ui.timeline_entry('心动盲盒礼物数据适配B站新改动')
            ui.timeline_entry(title='Release of 0.22.2-alpha', subtitle='2025-03-08', avatar='static/logo.ico')
            ui.timeline_entry('新增更新日志，仅在更新后第一次启动时自动显示')
            ui.timeline_entry(title='Release of 0.22.1-alpha', subtitle='2025-03-08', avatar='static/logo.ico')
            ui.timeline_entry('修复因为获取B站图片函数无法解析本地图片导致报错从而无法触发舰队礼物规则的问题')
            ui.timeline_entry('适配1080p + 125%缩放：收到礼物列表高度减半，调整窗体大小，调整about按钮位置')
            ui.timeline_entry('修复程序初始化因意外情况中止导致的数据损坏，会在继承倒计时数据时报错的问题')
            ui.timeline_entry('尝试修复未设定的盲盒也会触发收到礼物列表的问题（待观察）')
            ui.timeline_entry(title='Release of 0.22.0-alpha', subtitle='2025-03-07', avatar='static/logo.ico')
            ui.timeline_entry('修改内置更新可能会导致依赖库未更新的问题')
            ui.timeline_entry('修复内置更新启动新进程后不会关闭cmd窗口的问题')
            ui.timeline_entry('手动更新礼物数据时不再会覆盖已设定的时长和统计数据')
            ui.timeline_entry('修改检查更新通知')
            ui.timeline_entry(title='Release of 0.21.1-alpha', subtitle='2025-03-07', avatar='static/logo.ico')
            ui.timeline_entry('新增内置更新功能')
            ui.timeline_entry('现在打包时不再会自动复制本地盲盒图片')
            ui.timeline_entry('更新礼物数据不再更新测试礼物')
            ui.timeline_entry('暂时禁用海外更新源')
            ui.timeline_entry(title='Release of 0.21.0-alpha', subtitle='2025-03-05', avatar='static/logo.ico')
            ui.timeline_entry('获取礼物数据新增从B站API获取')
            ui.timeline_entry('移除storage初始化临时修复代码')
            ui.timeline_entry('更新nicegui至v2.12.1')
            ui.timeline_entry(title='Release of 0.20.1-alpha', subtitle='2025-02-14', avatar='static/logo.ico')
            ui.timeline_entry('修复about页面因为无法访问海外服务器返回500错误的问题')
            ui.timeline_entry(title='Release of 0.20.0-alpha', subtitle='2025-02-13', avatar='static/logo.ico')
            ui.timeline_entry('爬虫适配B站情人节新版礼物列表（移除pk礼物')
            ui.timeline_entry('补全盲盒数据')
            ui.timeline_entry('现在礼物设置可以直接指定盲盒或特定的盲盒礼物，特定礼物规则会覆盖盲盒规则')
            ui.timeline_entry(title='Release of 0.19.1-alpha', subtitle='2025-02-13', avatar='static/logo.ico')
            ui.timeline_entry('手动更新礼物数据时会更新预定义的盲盒数据')
            ui.timeline_entry('修复中国服务器检查更新返回值错误的问题')
            ui.timeline_entry('修复手动更新礼物数据时不会更新投喂挑战数据的问题')
            ui.timeline_entry('修复重置计数二次确认后不会关闭弹窗的问题')
            ui.timeline_entry('......', title='0.9.1-alpha ~ 0.19.0-alpha', subtitle='2025', avatar='static/logo.ico')
            ui.timeline_entry('Initial commit', title='Release of 0.9.0-alpha', subtitle='2025-01-19', avatar='static/logo.ico')