[project]
name = "bili-travail-server"
version = "0.31.6-alpha"
description = "加班姬服务端"
authors = [
    {name = "Nya-WSL"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9,<3.14"
dependencies = [
    "uvicorn (>=0.38.0,<1.0.0)",
    "fastapi (>=0.115.11,<1.0.0)",
    "python-multipart (>=0.0.20,<0.0.21)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "mirrors"
url = "https://mirrors.ustc.edu.cn/pypi/simple"
priority = "primary"